### ISSUE TITLE
Run Code

### ISSUE THREAD

**Issue by Yuhan291** [JackAILab/DTPNet#1]
Hello

Can I know how this code works? How do I remove the rain from my images?

Thanks

**Comment by JackAILab** [comment]
Thank you for your attention. You can install the environment package in requirement.txt and then run the main.py file. We have updated the detailed data preparation and training file. If you have further questions, please feel free to ask.

**Comment by JackAILab** [comment]
Thank you for your attention. You can install the environment package in requirement.txt and then run the main.py file. We have updated the detailed data preparation and training file. If you have further questions, please feel free to ask.

> Hello
> 
> Can I know how this code works? How do I remove the rain from my images?
> 
> Thanks

Thank you for your attention. You can install the environment package in requirement.txt and then run the main.py file. We have updated the detailed data preparation and training file. If you have further questions, please feel free to ask.
